# Run integration tests inside its own container
# Read more: https://github.com/kth/evolene#integration-testing
version: "3.2"

services:
  integration_tests:
    build: .
    image: $LOCAL_IMAGE_ID
    tty: true
    command: >
      sh -c "apk add openssl &&
             npm ci &&
             npm run test:integration"
    environment:
      - CANVAS_API_URL=https://kth.beta.instructure.com/api/v1
      - CANVAS_API_KEY
      - AZURE_SHARED_ACCESS_KEY_NAME
      - AZURE_SHARED_ACCESS_KEY
