trigger: none
pr:
  - master

variables:
  - group: elarande-general-params
  - group: elarande-secrets
  - name: imageName
    value: lms-sync-users
  - name: dockerfilePath
    value: "$(Pipeline.Workspace)/github/Dockerfile"
  - name: tag
    value: "$(Build.SourceVersion)"
  - name: parametersFileName
    value: pr.parameters.json


resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: templates/test/docker-test.yml@cet-iac
    parameters:
      dockerComposeFilePaths:
        - "$(Pipeline.Workspace)/github/docker-compose-unit-tests.yml"
        - "$(Pipeline.Workspace)/github/docker-compose-integration-tests.yml"
      dockerfilePath: $(dockerfilePath)
      imageName: $(imageName)
      tag: $(tag)
