pr: none
trigger:
  branches:
    include:
      - master

variables:
  - group: elarande-general-params
  - group: elarande-spoke1-ref
  - group: elarande-secrets
  - name: dockerfilePath
    value: "$(Pipeline.Workspace)/github/Dockerfile"
  - name: appName
    value: lms-sync-users-ref
  - name: imageName
    value: lms-sync-users
  - name: tag
    value: "${BUILD_BUILDNUMBER}_${BUILD_SOURCEVERSION:0:4}"
  - name: parametersFileName
    value: ref.parameters.json

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: templates/docker/build.yml@cet-iac
    parameters:
      runScan: false
      dockerFilePath: $(dockerfilePath)
      imageName: $(imageName)
      tag: $(tag)

  - bash: |
      echo "##vso[task.setvariable variable=tag;]${{ parameters.tag }}"

  - task: DockerCompose@0
    displayName: 'Unit test'
    inputs:
      dockerComposeFile: "$(Pipeline.Workspace)/github/docker-compose-unit-tests.yml"
      dockerComposeCommand: 'up'
      arguments: '--build --no-log-prefix --quiet-pull --abort-on-container-exit --always-recreate-deps --force-recreate'
      dockerComposeFileArgs: 'LOCAL_IMAGE_ID=$(containerRegistryUrl)/$(imageName):$(tag)'
    env:
      DOCKER_BUILDKIT: 1

  - task: DockerCompose@0
    displayName: 'Integration test'
    inputs:
      dockerComposeFile: "$(Pipeline.Workspace)/github/docker-compose-integration-tests.yml"
      dockerComposeCommand: 'up'
      arguments: '--build --no-log-prefix --quiet-pull --abort-on-container-exit --always-recreate-deps --force-recreate'
      dockerComposeFileArgs: 'LOCAL_IMAGE_ID=$(containerRegistryUrl)/$(imageName):$(tag)'
    env:
      DOCKER_BUILDKIT: 1
      AZURE_SHARED_ACCESS_KEY: $(AZURE_SHARED_ACCESS_KEY)
      AZURE_SHARED_ACCESS_KEY_NAME: $(AZURE_SHARED_ACCESS_KEY_NAME)
      CANVAS_API_KEY: $(CANVAS_API_KEY)

  - template: templates/docker/push.yml@cet-iac
    parameters:
      dockerFilePath: $(dockerfilePath)
      imageName: $(imageName)
      tag: $(tag)

  - template: templates/app-service/update-image.yml@cet-iac
    parameters:
      parametersFileName: $(parametersFileName)
      appName: $(appName)
      imageName: $(imageName)
      tag: $(tag)
      isApi: false
      hasSlot: false
